### ISSUE TITLE
def quantize_onnx(onnx_path, quantized_onnx_path): 

### ISSUE THREAD

**Issue by henbucuoshanghai** [dsindex/iclassifier#3]
def quantize_onnx(onnx_path, quantized_onnx_path):
    """
    Quantize the weights

the code in this py is pth to onnx?why you do this convert?the onnx is better?
how to use the onnx?

**Comment by dsindex** [comment]
@henbucuoshanghai 

check a post about `transformers + onnxruntime`
https://medium.com/microsoftazure/accelerate-your-nlp-pipelines-using-hugging-face-transformers-and-onnx-runtime-2443578f4333

usage here described at
https://github.com/dsindex/iclassifier/blob/master/OPTIMIZATION.md#conversion-pytorch-model-to-onnx-format-inference-with-onnxruntime
